### ISSUE TITLE
improve ES6 import syntax

### ISSUE THREAD

**Issue by thg303** [Microsoft/TypeScriptSamples#110] opened 2016-07-31 08:43 UTC
It's a feature request issue about fixing traditional **import** syntax for ES6. 
I think it would be better for developers and the editors auto-completion mechanism to transform original import syntax from:
`import { ComponentName } from 'path/to/module';`
to
`from 'path/to/module' import { ComponentName }`
or something like that **which improves auto-completion results**.

**Comment by DanielRosenwasser** [comment] 2016-08-02 19:15
Wrong repo, and duplicate of

* https://github.com/Microsoft/TypeScript/issues/7793
* https://github.com/Microsoft/TypeScript/issues/5821
* https://github.com/Microsoft/TypeScript/issues/5029
* https://github.com/Microsoft/TypeScript/issues/2371
* https://github.com/Microsoft/TypeScript/issues/4880

Check out the conversation in those issues.

**Closed by DanielRosenwasser** 2016-08-02 19:15 UTC
